name: Improvement Suggestion
description: Suggest an improvement or new feature
title: '[SUGGESTION] '
labels: ['enhancement']
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to suggest an improvement!

    - type: textarea
      id: description
      attributes:
          label: Description
          description: A detailed description of the suggestion
          placeholder: 'Describe your suggestion'
      validations:
          required: true

    - type: textarea
      id: benefits
      attributes:
          label: Benefits
          description: Describe the benefits of this suggestion
          placeholder: 'Benefits of the suggestion'
      validations:
          required: true

    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives
          description: Describe any alternative solutions or features you've considered
          placeholder: 'Alternative solutions'
      validations:
          required: false

    - type: textarea
      id: additional
      attributes:
          label: Additional Context
          description: Add any other context or screenshots about the suggestion here
          placeholder: 'Additional context'
